name: Test Node.js on Multiple Linux Distributions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, debian-11, centos-8]   # เพิ่ม OS ต่างๆ
        node-version: [18.x, 20.x, 22.x]                    # Node.js เวอร์ชันที่ต้องการทดสอบ

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
